spring.application.name=HackZone
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://localhost:8889/HackZone
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jwt.secret=UneCleSuperSecretePourHackZoneQuiFaitPlusDe32CaracteresPourLaSecurite!!!
#duree
jwt.expiration=3600000  